<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lumen.Core\Lumen.Core.csproj" />
    <ProjectReference Include="..\Lumen.Presentation\Lumen.Presentation.csproj" />
  </ItemGroup>

</Project>
