<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lumen.Core\Lumen.Core.csproj" />
    <ProjectReference Include="..\..\src\Lumen.Security\Lumen.Security.csproj" />
    <ProjectReference Include="..\..\src\Lumen.Storage\Lumen.Storage.csproj" />
    <ProjectReference Include="..\..\src\Lumen.Diagnostics\Lumen.Diagnostics.csproj" />
    <ProjectReference Include="..\..\src\Lumen.Roblox\Lumen.Roblox.csproj" />
    <ProjectReference Include="..\..\src\Lumen.Accounts\Lumen.Accounts.csproj" />
    <ProjectReference Include="..\..\src\Lumen.Mods\Lumen.Mods.csproj" />
    <ProjectReference Include="..\..\src\Lumen.Profiles\Lumen.Profiles.csproj" />
    <ProjectReference Include="..\..\src\Lumen.UI\Lumen.UI.csproj" />
  </ItemGroup>

</Project>
